global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "application-metrics"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["tangy-pancake-production.up.railway.app:443"]
    scheme: "https"