name: Deployment to Railway

on:
  push:
    branches: [main]

env:
  RAILWAY_SERVICE_NAME: ${{ secrets.RAILWAY_SERVICE_NAME }}
  RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Node modules with npm
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: Display status of Node modules
        continue-on-error: true
        run: npm list

      - name: Use Node version 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install relevant Yarn packages
        run: yarn install --frozen-lockfile

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Deploy to Railway
        run: railway up --service $RAILWAY_SERVICE_NAME
